spring:
  datasource:
    url: jdbc:h2:mem:rotinalize;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console


# Configuração IA
langchain4j:
  open-ai:
    chat-model:
      api-key:
      model-name: gpt-5-nano
      log-requests: true
      log-responses: true

# Configuração segurança (JWT)
jwt:
  private:
    key: "classpath:app.key"
  public:
    key: "classpath:app.pub"