# Configuração banco
#spring:
  #datasource:
    #url: jdbc:postgresql://localhost:5432/bancoRotinalize
    #driver-class-name: org.postgresql.Driver
    #username: postgres
    #password: "123456"
datasource:
  url: jdbc:h2:mem:rotinalize;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  driver-class-name: org.h2.Driver
  username: sa
  password: ""
  h2:
    console:
      enabled: true
      path: /h2-console # Você poderá ver o banco em http://localhost:8080/h2-console
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect # <<< Adicione/mude para H2
        #dialect: org.hibernate.dialect.PostgreSQLDialect

# Configuração IA
langchain4j:
  open-ai:
    chat-model:
      api-key:
      model-name: gpt-5-nano
      log-requests: true
      log-responses: true

# Configuração segurança (JWT)
jwt:
  private:
    key: "classpath:app.key"
  public:
    key: "classpath:app.pub"