# Configuração banco
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bancoRotinalize
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: "123456"
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configuração IA
langchain4j:
  open-ai:
    chat-model:
      api-key:
      model-name: gpt-5-nano
      log-requests: true
      log-responses: true

# Configuração segurança (JWT)
jwt:
  private:
    key: "classpath:app.key"
  public:
    key: "classpath:app.pub"