# Configuração Banco
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rotinalize
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect


# Configuração e-mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: rotinalize1@gmail.com
    password: rssyeywlffohjmae
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# Configuração IA
langchain4j:
  open-ai:
    chat-model:
      api-key:
      model-name: gpt-5-nano
      log-requests: true
      log-responses: true

# Configuração segurança (JWT)
jwt:
  private:
    key: "classpath:app.key"
  public:
    key: "classpath:app.pub"